library(org.Hs.eg.db)
library(annotate)
library(biomaRt)
library(dplyr)
library(stringr)
#Import List of HGNC Symbol Gene Names
GeneList <- read.delim(here::here("data", "GeneNames.txt"), stringsAsFactors=F)
#Connect to Ensembl database
hsmart <- useMart(dataset = "hsapiens_gene_ensembl", biomart = "ensembl")
hsmart
#Convert HGNC Symbols to HGNC IDs
ConvertedList <- getBM(
  attributes = c('ensembl_gene_id', 'hgnc_symbol','hgnc_id'), 
  filters = 'hgnc_symbol',
  values = GeneList,
  mart = hsmart)
#Remove extra text "HGNC:" from start of HGNC IDs
ConvertedList$hgnc_id<- gsub(pattern = "HGNC:",
                       replacement = "",as.character(ConvertedList$hgnc_id))
#Convert IDs to numeric values
ConvertedList$hgnc_id<-as.numeric(ConvertedList$hgnc_id)
#Export file
write.table(ConvertedList, file="ConvertedList.txt", append = FALSE, sep = ",", dec = " ",row.names = TRUE, col.names = TRUE)
